import { Vendor, Product } from './types';

// Default vendor setting for Irashop (+229 64 40 44 10)
export const MOCK_VENDOR: Vendor = {
  uid: 'vendor_irashop',
  storeName: 'Irashop',
  slug: 'irashop',
  whatsappNumber: '22964404410',
  description: 'Boutique de mode et articles de qualité au Bénin. Commandez facilement sur WhatsApp.',
  logoUrl: '/shops/irashop/irashop-prod-1.jpg',
  createdAt: new Date().toISOString(),
  subscriptionStatus: 'active',
  trialEndDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
};

export const MOCK_PRODUCTS: Product[] = [
  {
    "id": "prod_1",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 3500,
    "currency": "FCFA",
    "description": "Tissu Vintage aux motifs graphiques et bruts à fort contraste.",
    "photoUrl": "/shops/irashop/irashop-prod-1.jpg",
    "badge": "best_seller",
    "rating": 4.8,
    "ratingCount": 17,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_2",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 3500,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage aux dégradés doux et motif tropical fluide.",
    "photoUrl": "/shops/irashop/irashop-prod-2.jpg",
    "badge": "new",
    "rating": 4.9,
    "ratingCount": 22,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_3",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 3500,
    "currency": "FCFA",
    "description": "Tissu Vintage aux motifs abstraits et géométriques.",
    "photoUrl": "/shops/irashop/irashop-prod-3.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 27,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_4",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 3500,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage avec rendu soyeux et drapé élégant.",
    "photoUrl": "/shops/irashop/irashop-prod-4.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 32,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_5",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 3500,
    "currency": "FCFA",
    "description": "Tissu Vintage aux teintes brutes et textures contrastées.",
    "photoUrl": "/shops/irashop/irashop-prod-5.jpg",
    "badge": "best_seller",
    "rating": 4.8,
    "ratingCount": 2,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_6",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 3500,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage aux nuances dégradées tropicales.",
    "photoUrl": "/shops/irashop/irashop-prod-6.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 7,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_7",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 3500,
    "currency": "FCFA",
    "description": "Tissu Vintage aux rayures franches et rendu mat.",
    "photoUrl": "/shops/irashop/irashop-prod-7.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 12,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_8",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 3500,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage au toucher fluide et finitions soignées.",
    "photoUrl": "/shops/irashop/irashop-prod-8.jpg",
    "badge": "new",
    "rating": 4.7,
    "ratingCount": 17,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_9",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 3500,
    "currency": "FCFA",
    "description": "Tissu Vintage traditionnel à fort caractère.",
    "photoUrl": "/shops/irashop/irashop-prod-9.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 22,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_10",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Moderne",
    "price": 4000,
    "currency": "FCFA",
    "description": "Ensemble de confection soignée et design moderne.",
    "photoUrl": "/shops/irashop/irashop-prod-10.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 27,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_11",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Élégant",
    "price": 4000,
    "currency": "FCFA",
    "description": "Tenue de qualité supérieure ajustée avec élégance.",
    "photoUrl": "/shops/irashop/irashop-prod-11.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 32,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_12",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Confort",
    "price": 4000,
    "currency": "FCFA",
    "description": "Tenue moderne et confortable pour toute occasion.",
    "photoUrl": "/shops/irashop/irashop-prod-12.jpg",
    "badge": "best_seller",
    "rating": 4.7,
    "ratingCount": 2,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_13",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Vintage tissé aux motifs géométriques et épurés.",
    "photoUrl": "/shops/irashop/irashop-prod-13.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 7,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_14",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage aux nuances douces et toucher soyeux.",
    "photoUrl": "/shops/irashop/irashop-prod-14.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 12,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_15",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Vintage haute résistance à fort contraste.",
    "photoUrl": "/shops/irashop/irashop-prod-15.jpg",
    "badge": "new",
    "rating": 5,
    "ratingCount": 17,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_16",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage aux dégradés subtils et légers.",
    "photoUrl": "/shops/irashop/irashop-prod-16.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 22,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_17",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Vintage aux motifs abstraits et authentiques.",
    "photoUrl": "/shops/irashop/irashop-prod-17.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 27,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_18",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage à dominante tropicale et souple.",
    "photoUrl": "/shops/irashop/irashop-prod-18.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 32,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_19",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Vintage d'exception aux motifs riches.",
    "photoUrl": "/shops/irashop/irashop-prod-19.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 2,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_20",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage fluide et très agréable à porter.",
    "photoUrl": "/shops/irashop/irashop-prod-20.jpg",
    "badge": "best_seller",
    "rating": 4.7,
    "ratingCount": 7,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_21",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Vintage d'inspiration traditionnelle.",
    "photoUrl": "/shops/irashop/irashop-prod-21.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 12,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_22",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage finitions premium.",
    "photoUrl": "/shops/irashop/irashop-prod-22.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 17,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_23",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Vintage robuste aux couleurs vives.",
    "photoUrl": "/shops/irashop/irashop-prod-23.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 22,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_24",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage au drapé souple et raffiné.",
    "photoUrl": "/shops/irashop/irashop-prod-24.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 27,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_25",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Vintage aux teintes mates et graphiques.",
    "photoUrl": "/shops/irashop/irashop-prod-25.jpg",
    "badge": "new",
    "rating": 4.8,
    "ratingCount": 32,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_26",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage aux nuances fondues.",
    "photoUrl": "/shops/irashop/irashop-prod-26.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 2,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_27",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Vintage haute qualité au rendu authentique.",
    "photoUrl": "/shops/irashop/irashop-prod-27.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 7,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_28",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage doux au coucher de soleil.",
    "photoUrl": "/shops/irashop/irashop-prod-28.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 12,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_29",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Vintage aux finitions brutes et motifs tribaux.",
    "photoUrl": "/shops/irashop/irashop-prod-29.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 17,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_30",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 4500,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage souple et soyeux.",
    "photoUrl": "/shops/irashop/irashop-prod-30.jpg",
    "badge": "best_seller",
    "rating": 4.9,
    "ratingCount": 22,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_31",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Rayé Vintage",
    "price": 9000,
    "currency": "FCFA",
    "description": "Tissu rayé vintage de haute qualité confectionné avec soin.",
    "photoUrl": "/shops/irashop/irashop-prod-31.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 27,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_32",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Rayé Vintage",
    "price": 9000,
    "currency": "FCFA",
    "description": "Tissu rayé vintage moderne porté avec élégance.",
    "photoUrl": "/shops/irashop/irashop-prod-32.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 32,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_33",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Rayé Vintage",
    "price": 9000,
    "currency": "FCFA",
    "description": "Tissu rayé vintage haut de gamme aux lignes épurées.",
    "photoUrl": "/shops/irashop/irashop-prod-33.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 2,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_34",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Rayé Vintage",
    "price": 9000,
    "currency": "FCFA",
    "description": "Tissu rayé vintage élégant pour cérémonies et sorties.",
    "photoUrl": "/shops/irashop/irashop-prod-34.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 7,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_35",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Rayé Vintage",
    "price": 9000,
    "currency": "FCFA",
    "description": "Tissu rayé vintage aux finitions supérieures.",
    "photoUrl": "/shops/irashop/irashop-prod-35.jpg",
    "badge": "new",
    "rating": 5,
    "ratingCount": 12,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_36",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Rayé Vintage",
    "price": 9000,
    "currency": "FCFA",
    "description": "Tissu rayé vintage chic et confortable.",
    "photoUrl": "/shops/irashop/irashop-prod-36.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 17,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_37",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Rayé Vintage",
    "price": 9000,
    "currency": "FCFA",
    "description": "Tissu rayé vintage noble et résistant.",
    "photoUrl": "/shops/irashop/irashop-prod-37.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 22,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_38",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Rayé Vintage",
    "price": 9000,
    "currency": "FCFA",
    "description": "Tissu rayé vintage aux motifs authentiques.",
    "photoUrl": "/shops/irashop/irashop-prod-38.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 27,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_39",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Rayé Vintage",
    "price": 9000,
    "currency": "FCFA",
    "description": "Tissu rayé vintage traditionnel réinventé.",
    "photoUrl": "/shops/irashop/irashop-prod-39.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 32,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_40",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Rayé Vintage",
    "price": 9000,
    "currency": "FCFA",
    "description": "Tissu rayé vintage moderne et raffiné.",
    "photoUrl": "/shops/irashop/irashop-prod-40.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 2,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_41",
    "vendorUid": "vendor_irashop",
    "name": "Tissu Semi-Vintage",
    "price": 9000,
    "currency": "FCFA",
    "description": "Tissu Semi-Vintage au style tropical et fluide.",
    "photoUrl": "/shops/irashop/irashop-prod-41.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 7,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  }
];

export const formatPrice = (price: number, currency: string = 'FCFA'): string => {
  return `${price.toLocaleString('fr-FR')} ${currency}`;
};
