import { Vendor, Product } from './types';

// Default vendor setting for Irashop (+229 64 40 44 10)
export const MOCK_VENDOR: Vendor = {
  uid: 'vendor_irashop',
  storeName: 'Irashop',
  slug: 'irashop',
  whatsappNumber: '22964404410',
  description: 'Boutique de mode et articles de qualité au Bénin. Commandez facilement sur WhatsApp.',
  logoUrl: '/shops/irashop/irashop-prod-1.jpg',
  createdAt: new Date().toISOString(),
  subscriptionStatus: 'active',
  trialEndDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
};

export const MOCK_PRODUCTS: Product[] = [
  {
    "id": "prod_1",
    "vendorUid": "vendor_irashop",
    "name": "Robe / Pagne Vintage Irashop #1",
    "price": 3500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-1.jpg",
    "badge": "best_seller",
    "rating": 4.8,
    "ratingCount": 17,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_2",
    "vendorUid": "vendor_irashop",
    "name": "Robe / Pagne Semi-Vintage Irashop #2",
    "price": 3500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-2.jpg",
    "badge": "new",
    "rating": 4.9,
    "ratingCount": 22,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_3",
    "vendorUid": "vendor_irashop",
    "name": "Robe / Pagne Vintage Irashop #3",
    "price": 3500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-3.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 27,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_4",
    "vendorUid": "vendor_irashop",
    "name": "Robe / Pagne Semi-Vintage Irashop #4",
    "price": 3500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-4.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 32,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_5",
    "vendorUid": "vendor_irashop",
    "name": "Robe / Pagne Vintage Irashop #5",
    "price": 3500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-5.jpg",
    "badge": "best_seller",
    "rating": 4.8,
    "ratingCount": 2,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_6",
    "vendorUid": "vendor_irashop",
    "name": "Robe / Pagne Semi-Vintage Irashop #6",
    "price": 3500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-6.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 7,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_7",
    "vendorUid": "vendor_irashop",
    "name": "Robe / Pagne Vintage Irashop #7",
    "price": 3500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-7.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 12,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_8",
    "vendorUid": "vendor_irashop",
    "name": "Robe / Pagne Semi-Vintage Irashop #8",
    "price": 3500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-8.jpg",
    "badge": "new",
    "rating": 4.7,
    "ratingCount": 17,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_9",
    "vendorUid": "vendor_irashop",
    "name": "Robe / Pagne Vintage Irashop #9",
    "price": 3500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-9.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 22,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_10",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble / Tenue Irashop #10",
    "price": 4000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-10.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 27,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_11",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble / Tenue Irashop #11",
    "price": 4000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-11.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 32,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_12",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble / Tenue Irashop #12",
    "price": 4000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-12.jpg",
    "badge": "best_seller",
    "rating": 4.7,
    "ratingCount": 2,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_13",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #13",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-13.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 7,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_14",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #14",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-14.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 12,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_15",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #15",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-15.jpg",
    "badge": "new",
    "rating": 5,
    "ratingCount": 17,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_16",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #16",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-16.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 22,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_17",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #17",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-17.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 27,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_18",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #18",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-18.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 32,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_19",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #19",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-19.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 2,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_20",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #20",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-20.jpg",
    "badge": "best_seller",
    "rating": 4.7,
    "ratingCount": 7,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_21",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #21",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-21.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 12,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_22",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #22",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-22.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 17,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_23",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #23",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-23.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 22,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_24",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #24",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-24.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 27,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_25",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #25",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-25.jpg",
    "badge": "new",
    "rating": 4.8,
    "ratingCount": 32,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_26",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #26",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-26.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 2,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_27",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #27",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-27.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 7,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_28",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #28",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-28.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 12,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_29",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #29",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-29.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 17,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_30",
    "vendorUid": "vendor_irashop",
    "name": "Modèle Tissu Tissé Irashop #30",
    "price": 4500,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-30.jpg",
    "badge": "best_seller",
    "rating": 4.9,
    "ratingCount": 22,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_31",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Rayé Haute Qualité Irashop #31",
    "price": 9000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-31.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 27,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_32",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Rayé Haute Qualité Irashop #32",
    "price": 9000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-32.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 32,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_33",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Rayé Haute Qualité Irashop #33",
    "price": 9000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-33.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 2,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_34",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Rayé Haute Qualité Irashop #34",
    "price": 9000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-34.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 7,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_35",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Rayé Haute Qualité Irashop #35",
    "price": 9000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-35.jpg",
    "badge": "new",
    "rating": 5,
    "ratingCount": 12,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_36",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Rayé Haute Qualité Irashop #36",
    "price": 9000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-36.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 17,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_37",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Rayé Haute Qualité Irashop #37",
    "price": 9000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-37.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 22,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_38",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Rayé Haute Qualité Irashop #38",
    "price": 9000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-38.jpg",
    "badge": "none",
    "rating": 4.9,
    "ratingCount": 27,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_39",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Rayé Haute Qualité Irashop #39",
    "price": 9000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-39.jpg",
    "badge": "none",
    "rating": 5,
    "ratingCount": 32,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "prod_40",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Rayé Haute Qualité Irashop #40",
    "price": 9000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-40.jpg",
    "badge": "none",
    "rating": 4.7,
    "ratingCount": 2,
    "isLimitedStock": true,
    "createdAt": "2025-01-01T00:00:00.000Z",
    "stockCount": 3
  },
  {
    "id": "prod_41",
    "vendorUid": "vendor_irashop",
    "name": "Ensemble Rayé Haute Qualité Irashop #41",
    "price": 9000,
    "currency": "FCFA",
    "description": "Article de qualité supérieure sélectionné par Irashop. Contact direct: +229 64 40 44 10.",
    "photoUrl": "/shops/irashop/irashop-prod-41.jpg",
    "badge": "none",
    "rating": 4.8,
    "ratingCount": 7,
    "isLimitedStock": false,
    "createdAt": "2025-01-01T00:00:00.000Z"
  }
];

export const formatPrice = (price: number, currency: string = 'FCFA'): string => {
  return `${price.toLocaleString('fr-FR')} ${currency}`;
};
